@url = http://localhost:5000/tanks-module

@tankId = d33872ce-f3d6-4d9e-9fea-b14255db410b

@shrimpId = 02d8c7c7-1b8c-48c6-a457-c7be51e56521

###
GET http://localhost:5000

###
GET {{url}}

###
GET {{url}}/tanks/{{tankId}}

###
POST {{url}}/tanks
Content-Type: application/json

{
    "setUpDate": "2024-07-15"
}

###
GET {{url}}/shrimps/{{shrimpId}}

###
POST {{url}}/shrimps
Content-Type: application/json

{
    "name": "RedRuby",
    "species": "Caridina",
    "tankId": "{{tankId}}"
}