// <auto-generated />
using System;
using Eshrimp.Modules.Tanks.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eshrimp.Modules.Tanks.Infrastructure.EF.Migrations
{
    [DbContext(typeof(TanksDbContext))]
    [Migration("20240723225636_EditTankAndShrimp")]
    partial class EditTankAndShrimp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tanks")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eshrimp.Modules.Tanks.Domain.Entities.Shrimp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.Property<Guid?>("TankId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("Shrimps", "tanks");
                });

            modelBuilder.Entity("Eshrimp.Modules.Tanks.Domain.Entities.Tank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SetUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tanks", "tanks");
                });

            modelBuilder.Entity("Eshrimp.Modules.Tanks.Domain.Entities.Shrimp", b =>
                {
                    b.HasOne("Eshrimp.Modules.Tanks.Domain.Entities.Tank", "Tank")
                        .WithMany("Shrimps")
                        .HasForeignKey("TankId");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("Eshrimp.Modules.Tanks.Domain.Entities.Tank", b =>
                {
                    b.Navigation("Shrimps");
                });
#pragma warning restore 612, 618
        }
    }
}
